export const quotes = [
    'Se não existe vida fora da Terra, então o universo é um grande desperdício de espaço.',
    'A vida é apenas uma visão momentânea das maravilhas deste assombroso universo, e é triste que tantos se desgastem sonhando com fantasias espirituais.',
    'O universo não foi feito à medida do ser humano, mas tampouco lhe é adverso: é-lhe indiferente.',
    'A unidade é a variedade, e a variedade na unidade é a lei suprema do universo.',
    'O tempo e o espaço são modos pelos quais pensamos e não condições nas quais vivemos.',
    'Diante da vastidão do tempo e da imensidão do universo, é um imenso prazer para mim dividir um planeta e uma época com você.',
    'Há duas coisas infinitas: o Universo e a tolice dos Homens.',
    'Tudo aquilo que o homem ignora, não existe para ele. Por isso o universo de cada um, se resume no tamanho de seu saber.',
    'Não existe nenhum caminho lógico para a descoberta das leis do Universo - o único caminho é o da intuição.',
    'Para mim, é muito melhor compreender o universo como ele realmente é do que persistir no engano, por mais satisfatório e tranquilizador que possa parecer.',
    'A ciência está atrás do que o universo realmente é, não do que nos faz sentir bem.',
    'Todo aquele que se dedica ao estudo da ciência chega a convencer-se de que nas leis do Universo se manifesta um Espírito sumamente superior ao do homem, e perante o qual nós, com os nossos poderes limitados, devemos humilhar-nos.',
    'Nós somos feitos de poeira de estrelas.',
    'O que é inconcebível a respeito do universo é que ele é absolutamente concebível.',
    'Eu posso prever o movimento dos astros, mas não consigo entender a loucuras dos homens.',
    'Há menos grãos de areia na Terra, do que estrelas no espaço.',
    'Eu não sou religioso no sentido normal. Eu acredito que o universo é governado pelas leis da ciência. As leis podem ter sido decretadas por Deus, mas Deus não intervém para quebrar as leis.',
    'O que eu fiz foi demonstrar que é possível determinar pelas leis da ciência o modo como o Universo começou. Neste caso, não é necessário apelar a Deus para explicar como começou o Universo. Se isto não prova que Deus não existe, pelo menos prova que Deus não é preciso para nada.',
    'O sentido da vida, é o que você quiser que ele seja. Nós somos o universo contemplando a si mesmo.',
    'Se você entende como o universo funciona, de certa forma pode controlá-lo.',
    'Por haver uma lei como a gravidade, o universo pode e irá criar a ele mesmo do nada. A criação espontânea é a razão pela qual algo existe ao invés de não existir nada, é a razão pela qual o universo existe, pela qual nós existimos.',
    'Em meio a toda essa vastidão do universo não há indício de que alguém virá de algum outro lugar para nos salvar de nós mesmos.',
    'Se você quiser fazer uma torta de maçã a partir do zero, você deve primeiro inventar o Universo.',
    'O universo não parece ser nem benevolente nem hostil, apenas indiferente às preocupações de criaturas tão insignificantes como nós.',
    'Quem é mais humilde: o cientista que olha para o Universo com uma mente aberta e aceita aquilo que o Universo tem para nos ensinar, ou alguém que diz "tudo o que está neste livro deve ser considerado a verdade literal e esqueçam a falibilidade dos humanos que o escreveram"?',
    'Por mais que o meu corpo seja limitado, minha mente é livre para explorar o universo.',
    'O universo é o pensamento divino materializado.',
    'Meu objetivo é simples. É a compreensão completa do universo, por que ele é assim e por que existe.',
    '“Olhem para as estrelas e aprendam com elas”',
    'Seria a Terra o hospício do Universo?',
    'O tempo e relativo.',
    'Nós não nos devemos surpreender das condições no universo serem adequadas para a vida, mas isso não é prova de que o universo foi desenhado para permitir a vida. Poderíamos chamar à ordem pelo nome de Deus, mas seria um Deus impessoal. Não há muito de pessoal sobre as leis da física.',
    'Uma das regras básicas do universo é que nada é perfeito. A perfeição simplesmente não existe. Sem imperfeição, nem você nem eu existiríamos.',
    'Não há poder de controle sobre o universo maior do que o poder que nos controla.',
    'Quando uma criança dorme, anjos se reúnem e cantam a pureza do universo, mamãe diz para falar baixo, para que o bebe sinta a sinfonia angelical da paz.',
    'Quão diferente tudo poderia ser em outro universo, todas as vidas que não vivemos...',
    'O universo não é indiferente a nossa existência – ele depende dela.',
    'Para criaturas pequenas como nós, a vastidão só é suportável através do amor.',
    'Às vezes acredito que há vida em outros planetas às vezes eu acredito que não. Em qualquer dos casos, a conclusão é assombrosa.',
    'Nós somos uma maneira do Cosmos conhecer a si mesmo',
    'Estamos irrevogavelmente em um caminho que nos levará às estrelas. A não ser que, por uma monstruosa capitulação ao egoísmo e à estupidez, acabemos nos destruindo.',
    'Não há morte que não seja plena, cheia, absoluta, para quem se vai e leva todo o universo consigo',
    'Nós somos uma espécie avançada de macacos em um planeta menor de uma estrela mediana. Mas nós conseguimos entender o universo. E isso nos torna muito especiais.',
    '"Primeiro, lembre de olhar para as estrelas e não para seus pés. Segundo, nunca desista do trabalho. O trabalho dá a você significado e propósito para a vida. Terceiro, se você tiver a sorte de encontrar o amor, lembre-se que está lá e não o jogue fora."',
    'O nitrogênio em nosso DNA, o cálcio em nossos dentes, o ferro em nosso sangue, o carbono em nossas tortas de maçã… Foram feitos no interior de estrelas em colapso, agora mortas há muito tempo. Nós somos poeira das estrelas.',
    'Nós somos apenas uma espécie avançada de macacos em um planeta pequeno de uma estrela bastante comum. Mas nós podemos entender o universo. Isso nos torna especial.',
    'Não importa o escuro e a imensidão de tuas noites, quero sempre acender estrelas no teu coração!',
    'Somos poeira das estrelas.',
    'Um milhão de luzes estão dançando e você está lá, uma estrela cadente.',
    'O cosmos é tudo o que existiu, existe ou existirá.',
    'As moléculas da vida enchem o cosmos.',
    'A luz das estrelas fixas é da mesma natureza que a luz do Sol.',
    '[Conselhos para os meus três filhos] Um, lembre-se de olhar para as estrelas e não para baixo, para seus pés. Dois, nunca desista do trabalho. Trabalho dá significado e propósito, e a vida está vazia sem eles. Três, se você tiver sorte o suficiente para encontrar o amor, não o deixe ir embora.',
    'Os Grandes, mesmo depois de partirem, hão de continuar a ser estrelas cintilantes para inspirarem a humanidade para grandes realizações.',
    'Somos os representantes do cosmos. Somos um exemplo do que o hidrogênio pode fazer com 15 bilhões de anos de evolução cósmica.',
    'Se ansiamos que nosso planeta seja importante, há algo que podemos fazer quanto a isso. Podemos fazer com que ele seja significativo com a coragem de nossas perguntas e a profundidade de nossas respostas.',
    '⁠Mesmo as estrelas, que parecem tão numerosas, são como areia, são como poeira – ou menos que poeira – na enormidade do espaço.',
    

]